import = [
  "~/.config/alacritty/themes/themes/rose-pine.toml",
]

[window]
opacity = 0.8

[font]
size = 8.25
normal = { family = "GoMonoNerdFont", style = "Regular" }
bold = { family = "GoMonoNerdFont", style = "Bold" }
italic = { family = "GoMonoNerdFont", style = "Italic" }
bold_italic = { family = "GoMonoNerdFont", style = "Bold Italic" }
